# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yam
subtitle: Yam
description: Yam的个人博客，记录学习，专注分享，yam博客
keywords: 博客，个人博客，分享，学习，软件，Yam，yam博客
author: Yam
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.it0114.xyz
root: /
permalink: :title/
#permalink: :year/:month/:day/:title/
permalink_defaults: 

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pure

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git 
  repository: git@github.com:it0114/it0114.github.io.git
  branch: master

# hexo-admin authentification
admin:
  username: admin
  password_hash: $2a$10$ZiotS0pJwNvEYMH988q4ueyIzGluJB1niHdiTkx8.xotalvtHRIxW
  secret: my love yanminyi
  deployCommand: 'sh hexo-deploy.sh'


baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: www.it0114.xyz # 在百度站长平台中注册的域名
  token: qjKkDQbvqitoec5Z # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里
  
# Security 文章加密
##
encrypt:
    enable: true
    
    
